### PR TITLE
style: Update HOMEPAGE_URL in CMakeLists.txt

### PR DESCRIPTION
**Pull request by Joker2770**
The value for the key of HOMEPAGE_URL is url-string type.

```cmake
project(<PROJECT-NAME>
        [VERSION <major>[.<minor>[.<patch>[.<tweak>]]]]
        [DESCRIPTION <project-description-string>]
        [HOMEPAGE_URL <url-string>]
        [LANGUAGES <language-name>...])
```

### CODE REVIEW

**Comment by Joker2770** [comment]
Once I built a snapcraft application and found the problem, the reference log as follow.

```
Building libsgfcplusplus 
+ snapcraftctl build
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
CMake Error: Could not find cmake module file: CMakeDetermineHOMEPAGE_URLCompiler.cmake
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_HOMEPAGE_URL_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_HOMEPAGE_URL_COMPILER
CMake Error: Could not find cmake module file: /build/qpiskvork/parts/libsgfcplusplus/build/CMakeFiles/3.10.2/CMakeHOMEPAGE_URLCompiler.cmake
CMake Error: Could not find cmake module file: CMakeDeterminehttps://github.com/herzbube/libsgfcplusplusCompiler.cmake
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_https://github.com/herzbube/libsgfcplusplus_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_https://github.com/herzbube/libsgfcplusplus_COMPILER
CMake Error: Could not find cmake module file: /build/qpiskvork/parts/libsgfcplusplus/build/CMakeFiles/3.10.2/CMakehttps://github.com/herzbube/libsgfcplusplusCompiler.cmake
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:10 (project):
  No CMAKE_HOMEPAGE_URL_COMPILER could be found.

  Tell CMake where to find the compiler by setting the CMake cache entry
  CMAKE_HOMEPAGE_URL_COMPILER to the full path to the compiler, or to the
  compiler name if it is in the PATH.


CMake Error: Could not find cmake module file: CMakeHOMEPAGE_URLInformation.cmake
CMake Error at CMakeLists.txt:10 (project):
  No CMAKE_https://github.com/herzbube/libsgfcplusplus_COMPILER could be
  found.

  Tell CMake where to find the compiler by setting the CMake cache entry
  CMAKE_https://github.com/herzbube/libsgfcplusplus_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


CMake Error: Could not find cmake module file: CMakehttps://github.com/herzbube/libsgfcplusplusInformation.cmake
CMake Error: CMAKE_HOMEPAGE_URL_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_https://github.com/herzbube/libsgfcplusplus_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/build/qpiskvork/parts/libsgfcplusplus/build/CMakeFiles/CMakeOutput.log".
```

**Comment by Joker2770** [comment]
Once I built a snapcraft application and found the problem, the reference log as follow.

```
Building libsgfcplusplus 
+ snapcraftctl build
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
CMake Error: Could not find cmake module file: CMakeDetermineHOMEPAGE_URLCompiler.cmake
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_HOMEPAGE_URL_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_HOMEPAGE_URL_COMPILER
CMake Error: Could not find cmake module file: /build/qpiskvork/parts/libsgfcplusplus/build/CMakeFiles/3.10.2/CMakeHOMEPAGE_URLCompiler.cmake
CMake Error: Could not find cmake module file: CMakeDeterminehttps://github.com/herzbube/libsgfcplusplusCompiler.cmake
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_https://github.com/herzbube/libsgfcplusplus_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_https://github.com/herzbube/libsgfcplusplus_COMPILER
CMake Error: Could not find cmake module file: /build/qpiskvork/parts/libsgfcplusplus/build/CMakeFiles/3.10.2/CMakehttps://github.com/herzbube/libsgfcplusplusCompiler.cmake
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:10 (project):
  No CMAKE_HOMEPAGE_URL_COMPILER could be found.

  Tell CMake where to find the compiler by setting the CMake cache entry
  CMAKE_HOMEPAGE_URL_COMPILER to the full path to the compiler, or to the
  compiler name if it is in the PATH.


CMake Error: Could not find cmake module file: CMakeHOMEPAGE_URLInformation.cmake
CMake Error at CMakeLists.txt:10 (project):
  No CMAKE_https://github.com/herzbube/libsgfcplusplus_COMPILER could be
  found.

  Tell CMake where to find the compiler by setting the CMake cache entry
  CMAKE_https://github.com/herzbube/libsgfcplusplus_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


CMake Error: Could not find cmake module file: CMakehttps://github.com/herzbube/libsgfcplusplusInformation.cmake
CMake Error: CMAKE_HOMEPAGE_URL_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_https://github.com/herzbube/libsgfcplusplus_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/build/qpiskvork/parts/libsgfcplusplus/build/CMakeFiles/CMakeOutput.log".
```

**Comment by Joker2770** [comment]
Once I built a snapcraft application and found the problem, the reference log as follow.

```
Building libsgfcplusplus 
+ snapcraftctl build
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
CMake Error: Could not find cmake module file: CMakeDetermineHOMEPAGE_URLCompiler.cmake
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_HOMEPAGE_URL_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_HOMEPAGE_URL_COMPILER
CMake Error: Could not find cmake module file: /build/qpiskvork/parts/libsgfcplusplus/build/CMakeFiles/3.10.2/CMakeHOMEPAGE_URLCompiler.cmake
CMake Error: Could not find cmake module file: CMakeDeterminehttps://github.com/herzbube/libsgfcplusplusCompiler.cmake
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_https://github.com/herzbube/libsgfcplusplus_COMPILER_ENV_VAR
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_https://github.com/herzbube/libsgfcplusplus_COMPILER
CMake Error: Could not find cmake module file: /build/qpiskvork/parts/libsgfcplusplus/build/CMakeFiles/3.10.2/CMakehttps://github.com/herzbube/libsgfcplusplusCompiler.cmake
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:10 (project):
  No CMAKE_HOMEPAGE_URL_COMPILER could be found.

  Tell CMake where to find the compiler by setting the CMake cache entry
  CMAKE_HOMEPAGE_URL_COMPILER to the full path to the compiler, or to the
  compiler name if it is in the PATH.


CMake Error: Could not find cmake module file: CMakeHOMEPAGE_URLInformation.cmake
CMake Error at CMakeLists.txt:10 (project):
  No CMAKE_https://github.com/herzbube/libsgfcplusplus_COMPILER could be
  found.

  Tell CMake where to find the compiler by setting the CMake cache entry
  CMAKE_https://github.com/herzbube/libsgfcplusplus_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


CMake Error: Could not find cmake module file: CMakehttps://github.com/herzbube/libsgfcplusplusInformation.cmake
CMake Error: CMAKE_HOMEPAGE_URL_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_https://github.com/herzbube/libsgfcplusplus_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/build/qpiskvork/parts/libsgfcplusplus/build/CMakeFiles/CMakeOutput.log".
```

**Comment by herzbube** [comment]
Thanks a lot for your contribution!

**Pull request merged**
